### ISSUE TITLE
Discrepancies between pressure computed with cpu (FFTW/AccFFT) and gpu (AccFFT)

### ISSUE THREAD

**Issue by novatig** [amirgholami/accfft#10]
Hi,

I'm having trouble at correctly solving a 3d poisson equation with the gpu library.
The cpu implementation and fftw yield the same result.

Here are the visualizations of a slice of the solution, the structure in the solution for the gpu suggests errors in communication (solution was obtained with 32 x 2 x 1  = 64 ranks):
![accfft_gpu](https://cloud.githubusercontent.com/assets/16716298/22116229/2157866a-de70-11e6-9969-131809829768.png)
![accfft_cpu](https://cloud.githubusercontent.com/assets/16716298/22116234/23e1497a-de70-11e6-8e49-c49b24cba278.png)

The code I'm using (accfft only) is, almost entirely taken from step 4:
[Solvers.zip](https://github.com/amirgholami/accfft/files/717225/Solvers.zip)

Compiled with cudatoolkit/8.0, fftw/3.3.4.10 and cray-mpich/7.5.0, only minor modifications to the code were required for compialtions (no major warning):
added #include < cstddef > in transpose_cuda
moved to last include #include "operators_gpu.txx" in #include operators_gpu.cpp
added #include < bitset > to operators_gpu.txx

Any ideas?

**Comment by amirgholami** [comment]
Hi,

I highly recommend using the operators in AccFFT for computing spectral transforms. Please see http://accfft.org/articles/step5/ for details

**Comment by novatig** [comment]
Hi,

Thanks for your time.

Am I doing something wrong in the poisson filter? Is the same as the one in step 4.

Also, could you give me more information on the operators? You need the size of the domain in order to be able to take the derivatives, but the operators do not require it. 
Does it assume an unit cube for the domain?

**Comment by amirgholami** [comment]
The AccFFT operators require the grid size to be even, and assume domain length is 2pi (you need to scale the output otherwise).

From the output images, it seems you are making an error in multiplying some of the frequencies. I suggest computing the error between AccFFT operator's output and yours to see in which step your code has a discrepancy.

**Comment by novatig** [comment]
Hi,

I don't understand a couple of things with void laplace_mult_wave_number_gpu_ in operators_cuda.

First, 
`
	int blocksInX = std::ceil(N[0] / 4.);
	int blocksInY = std::ceil(N[1] / 4.);
	int blocksInZ = std::ceil(N[2] / 4.);

	dim3 Dg(blocksInX, blocksInY, blocksInZ);
	dim3 Db(4, 4, 4);
	laplace_mult_wave_number_cu<<<Dg, Db>>>(wA, A,n_gpu,osize_gpu,ostart_gpu,scale);
`
Shouldn't the blocks over which the gpu operates have size osize[0], osize[1], osize[2]?

Also, in the kernel laplace_mult_wave_number_cu:
`
	wave=-wx*wx-wy*wy-wz*wz;
	ptr=(i*osize[1]+j)*osize[2]+k;
	wA[ptr][0] = scale*wave*A[ptr][0];
	wA[ptr][1] = scale*wave*A[ptr][1];
`
Shouldn't it be wA[ptr][0] = scale*A[ptr][0]/wave;

Thanks again for your time.

**Comment by novatig** [comment]
Ok solved the issue with this kernel:
[PoissonSolverScalarFFTW_ACC.cu.zip](https://github.com/amirgholami/accfft/files/717953/PoissonSolverScalarFFTW_ACC.cu.zip)
(the rest of the solver is the same as included above)

I think that step4 might be out of date, anything related to these comments looks guilty:
  	// CUDA X dir maps isize[2]
  	// CUDA Y dir maps isize[1]
  	// isize[0] is sweeped inside kernel

Also, in my implementation i did  wA[ptr][0] = scale*A[ptr][0]/wave; and got the same result as with fftw and accfft with cpu.

Thanks for your work on this library :)
