### ISSUE TITLE
MPI C++ bindings are deprecated

### ISSUE THREAD

**Issue by pkestene** [amirgholami/accfft#16]
Hi,

I noticed the use of type MPI::BOOL from the c++ MPI bindings, but this is deprecated and not always available on some cluster.

I suggest to change "MPI::BOOL" into "par::Mpi_datatype<bool>::value()" which is defined in header dtypes.h

**Comment by amirgholami** [comment]
Many thanks Pierre for the pull request. It should be fixed now
