### ISSUE TITLE
installation notes on NCSA Blue Waters

### ISSUE THREAD

**Issue by spiralgen** [amirgholami/accfft#4]
Let me know if you would rather this info go through email.

Following the installation instructions:
http://accfft.org/articles/install/

mkdir build
cd build/
~/accfft/build>cmake ./build
...
CMake Error: The source directory "/u/sciteam/jml37/accfft/build" does not appear to contain CMakeLists.txt.

If I:

cp ../CMakeLists.txt ./
~/accfft/build>cmake
...
In-source builds not allowed.  Please make a new directory (called a build
  directory) and run CMake from there.

Working out of the top-level dir works for me:

~/accfft> cmake ./build

My cmake version is:

~/accfft> cmake --version
cmake version 3.1.3

**Comment by pkestene** [comment]
Hi,

in the build directory, you need to provide path to source.
So in your case, you should use cmake like this:
~/accfft/build>cmake ..

It is not correct to manually copy a CMakelist.txt inside the build directory.

**Comment by spiralgen** [comment]
Thanks, that makes sense.  Solutions to the error usually included hacking and cp CMakeLists.txt into build.  Also, the instructions did not read "cmake .." explicitly.  Thanks for the help.
